### ISSUE TITLE
Configure Replacement

### ISSUE THREAD

**Issue by signalwerk** [networkteam/Networkteam.Neos.MailObfuscator#10]
It would be awesome to have the option to configure the @-Replacement by a config file. Personally I prefere something like `@ → <!-- pre @ -->@<!--- post @ --><span style="display: none;">post @</span>`
Could you probably point me to a reference, where I can have a look how to do it then I would try a pull request.

**Comment by monofone** [comment]
I'ts now possible by configuring 

```
Networkteam:
  Neos:
    MailObfuscator:
      atCharReplacementString: ' (ät) '
```
There you can put whatever you want.
