### ISSUE TITLE
replace ( at ) width a gif

### ISSUE THREAD

**Issue by stefkey** [networkteam/Networkteam.Neos.MailObfuscator#5]
Hi, thanks a lot for this package! I found the RewriteAtCharConverter.php who replace the @ sign.
Its possible to insert a .gif grafik instead the ( at ) ?
Can you help me for the php-code, i'am not a programmer :-(

```
class RewriteAtCharConverter implements EmailLinkNameConverterInterface {

    /**
     * @param string $emailAddress
     * @return string
     */
    public function convert($emailAddress) {
        return str_replace('@', ' (at) ', $emailAddress);
    }
}
```

**Comment by hlubek** [comment]
Hi @stefkey,

yes, you could use the `ResourceManager` from Flow to get the URL to a resource and use that in the replacement string inside an image tag. That's quite easy but hard if you're not into PHP and Flow development ;)

I'll see if we can include an example for that case.

**Comment by monofone** [comment]
Hi you can include an image tag like this:
```
Networkteam:
  Neos:
    MailObfuscator:
      atCharReplacementString: '<img src="http://icons.iconarchive.com/icons/chromatix/keyboard-keys/32/at-icon.png" alt="at" />'
```
